# Generated by Django 4.2.1 on 2023-06-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
